### ISSUE TITLE
Aclarar la licencia

### ISSUE THREAD

**Issue by HyperChocolat** [zumberr/Nekotinaclone#3]
No entendi nada :moyai:

**Comment by HyperChocolat** [comment]
No puede ser no se escribir licencia

**Comment by zumberr** [comment]
hola respetando la licencia del codigo a mi persona no habra probema
con referente a la licencia tienes algun otro problema?

**Comment by HyperChocolat** [comment]
> hola respetando la licencia del codigo a mi persona no habra probema con referente a la licencia tienes algun otro problema?

Hablo de un archivo LICENSE. realmente tambien lei el readme.md pero no entendi especificamente que terminos se deben de cumplir

**Comment by zumberr** [comment]
solamente respetar los derechos de autor 
Ya sea en un read.md 
o simplemente poniendolo en alguna parte del codigo

volvere a editar estos archivos para hacerlos mas claros

**Comment by HyperChocolat** [comment]
> solamente respetar los derechos de autor Ya sea en un read.md o simplemente poniendolo en alguna parte del codigo
> 
> volvere a editar estos archivos para hacerlos mas claros

Sankius
